### ISSUE TITLE
Compiler accepts duplicate name definitions

### ISSUE THREAD

**Issue by d-xo** [ethlts/solcore#13]
Methods declared in classes are currently introduced unqualified into the global scope, but the compiler does not forbid duplicated method names. This leads to surprising behavior (that is dependent on the order of declarations):

```
class self:A {
  function foo(p : self) -> Word;
}

class self:B {
  function foo(p : self) -> Word;
}

instance Word:B {
  function foo(x : Word) -> Word {
    return x;
  }
}

// error: Constraint for A not found in type of foo
instance Word:A {
  function foo(x : Word) -> Word {
    return x;
  }
}
```

I'm not sure what the best solution is here. Haskell forbids duplicated class method names, but it's a bit clunky, perhaps something like the way that lean does it (by namespacing class methods under the class name) is nicer?

**Comment by rodrigogribeiro** [comment]
A simple fix is now at `main`: it rejects duplicated definitions.

**Comment by rodrigogribeiro** [comment]
Fixed in `main`.
