### ISSUE TITLE
Class hierarchies

### ISSUE THREAD

**Issue by d-xo** [ethlts/solcore#15]
It would be nice to be able to define some kind of class hierarchy (e.g. functor -> applicative -> monad). The motivating example from the standard library is for reference types (some of which are read only, and some of which are read/write). I know of two approaches here:

1. Haskell: class constraints

2. Lean: structure inheritance ([docs](https://lean-lang.org/theorem_proving_in_lean4/structures_and_records.html#inheritance))

```
class ref:Loadable (deref) {
    load : ref -> deref;
};

class ref:Storable (deref) {
    store : ref -> deref -> Unit;
};

// haskell style class constraints
class (Loadable ref deref, Storable ref deref) => ref:Ref (deref) {};

// lean style inheritance
class ref:Ref (deref) extends Loadable(ref, deref), storable(ref, deref) {};
```

**Comment by rodrigogribeiro** [comment]
Fixed on `main`.
