### ISSUE TITLE
Compiler allows incomplete instance definitions without error

### ISSUE THREAD

**Issue by Y-Nak** [ethlts/solcore#17]
The code below is compiled without any errors.
```
class self : Foo {
    function f(x: self) -> self;
}

instance Word : Foo {
}
```

**Comment by rodrigogribeiro** [comment]
This is something that we should decide what the language should do. Haskell do not report a type error for a similar code fragment, but it reports an warning. What should be the best strategy here? Consider it an error or a simple warning for the user?
