### ISSUE TITLE
Type Checker Loops (possibly due to missing Bound Variable Restriction)

### ISSUE THREAD

**Issue by ekpyron** [ethlts/solcore#20]
On this test case:
```solidity
class a:D { function f(x:a); }
class a:F(b) {}

data Memory(a) = Memory(Word)

instance Memory(a):F(Memory(Memory(Memory(a)))) {}
instance (c:D,a:F(c)) => Memory(Memory(Memory(a))):D {
    function f(x:Memory(Memory(Memory(a)))) {}
}

function g(y:b) {
    let x : Memory(Memory(Memory(Memory(b))));
    f(x);
}
```
sol-core doesn't seem to terminate.

This was an attempt of constructing a case similar to Example 15 in https://www.comp.nus.edu.sg/~gregory/papers/jfp07.pdf, causing problems due to violating the Bound Variable Restriction.

Surprisingly, if I replace ``b`` with a concrete type, it terminates (with an error):
If I replace ``b`` in the above with a concrete type (``Word``), so if I use this:
```solidity
class a:D { function f(x:a); }
class a:F(b) {}

data Memory(a) = Memory(Word)

instance Memory(a):F(Memory(Memory(Memory(a)))) {}
instance (c:D,a:F(c)) => Memory(Memory(Memory(a))):D {
    function f(x:Memory(Memory(Memory(a)))) {}
}

function g() {
    let x : Memory(Memory(Memory(Memory(Word))));
    f(x);
}
```
solc-core does *not* loop, but gives me:
```
no instance of Word : F (Memory(Memory(Memory(Word))))
Known instances:
(b ~ Memory(Memory(Memory(a)))) => Memory(a) : F (b)

 - in:Memory(Memory(Memory(Memory(Word)))) : D
```

Another similar reconstruction of Example 15 in https://www.comp.nus.edu.sg/~gregory/papers/jfp07.pdf with an additional application of ``Memory`` in the instance of ``F`` makes solc-core also loops with a concrete type, so the following also loops:

```solidity
class a:D { function f(x:a); }
class a:F(b) {}

data Memory(a) = Memory(Word)

instance Memory(a):F(Memory(Memory(Memory(Memory(a))))) {}
instance (c:D,a:F(c)) => Memory(Memory(Memory(a))):D {
    function f(x:Memory(Memory(Memory(a)))) {}
}

function g() {
    let x : Memory(Memory(Memory(Memory(Word))));
    f(x);
}
```

Surprisingly, if I switch the context assumptions in the instance of ``D``, so if I use:
```solidity
class a:D { function f(x:a); }
class a:F(b) {}

data Memory(a) = Memory(Word)

instance Memory(a):F(Memory(Memory(Memory(a)))) {}
instance (a:F(c),c:D) => Memory(Memory(Memory(a))):D {
    function f(x:Memory(Memory(Memory(a)))) {}
}

function g(y:b) {
    let x : Memory(Memory(Memory(Memory(b))));
    f(x);
}
```
instead, then solc-core fails hitting the reduction limit:
```
Max context reduction depth exceeded
 - in:Memory(Memory(Memory(b))) : D
```

So I guess the former cases even bypass the reduction depth limit?

**Comment by rodrigogribeiro** [comment]
Fixed in last commit on `main` by implementing the bound variable condition.
