### ISSUE TITLE
Oddity with nested phantom types.

### ISSUE THREAD

**Issue by ekpyron** [ethlts/solcore#21]
This works:
```solidity
data Memory(a) = Memory(Word)

function g() {
    let x : Memory(Memory(Word));
    x = Memory(0);
}
```
while this fails:
```solidity
data Memory(a) = Memory(Word)

function g() {
    let x : Memory(Memory(Word)) = Memory(0);
}
```
with 
```
Types do not match: Memory(Word) and b
 - in:let x :: Memory(Memory(Word)) = Memory(0) ;
```

Am I missing something here? I'd have expected the latter to work as well.

**Comment by rodrigogribeiro** [comment]
Fixed on `main`.

**Comment by ekpyron** [comment]
For me on ``main`` now in fact *both* cases no longer work ;-).

**Comment by rodrigogribeiro** [comment]
This is now fixed at `main`. Please confirm either by running `cabal new-test` or by running the compiler over the files `test/examples/cases/Memory1.solc` and `test/examples/cases/Memory2.solc`.
