### ISSUE TITLE
Minor bugs in Yul syntax in assembly blocks

### ISSUE THREAD

**Issue by mbenke** [ethlts/solcore#7]
There are two problems with the Yul syntax in SolcoreParser.y:

- IdentifierList should be nonempty
- there are no semicolons in Yul (see https://docs.soliditylang.org/en/latest/yul.html#formal-specification), hence I propose making them optional

Test case:

```
contract Add1 {
  function main() {
    let res: Word;
    assembly {
       res := add(40, 2)
    };
    return res;
  }
}
```

I am going to propose a PR to fix these issues.

**Comment by rodrigogribeiro** [comment]
Merged.
